### ISSUE TITLE
Ethernet isn't stable

### ISSUE THREAD

**Issue by macpromax** [Bhavinjain260/Hackintosh-dell-inspiron-5559#2]
I have an issue with my ethernet on my DELL Inspiron 5559 running Monterey in OpenCore 0.7.7 when I unplug / plug my ethernet cable. The RTL8100.kext it work fine at boot and but not if I unplug and replug my ethernet cable, it says. "Ethernet has a self-assigned IP address and will not be able to connect to the Internet"

**Comment by Bhavinjain260** [comment]
Try this fix 
1-remove ethernet cable
2-run ifconfig ... down
3-run ifconfig ... up
4-plug the cable back in

**Comment by macpromax** [comment]
Problem Solved. Thank you so much. 

Commands
sudo ifconfig en0 down
sudo ifconfig en0 up
