### ISSUE TITLE
Heat up issue  MACS FAN CONTROL "No fans detected, please try to reset the SMC"

### ISSUE THREAD

**Issue by macpromax** [Bhavinjain260/Hackintosh-dell-inspiron-5559#3]
I'm facing heat up and battery draining issues with my Dell Inspiron 5559 laptop CPU: Core i5 6200u Opencore 0.7.7. I try to use  MACS FAN CONTROL application but facing this error "No fans detected, please try to reset the SMC". Please help me fix this problem. 

![Screen Shot 2022-01-30 at 12 28 33 PM](https://user-images.githubusercontent.com/98261478/151690918-e0a9542f-71b6-49d1-9108-5a6d16fbf4ae.png)

**Comment by Bhavinjain260** [comment]
are you using smcdellsensor.kext?

**Comment by macpromax** [comment]
No, I'm not using this kext. Here is my EFI.

https://drive.google.com/file/d/10aszDx5OMABm1QamRtykjIyNBtLmyO91/view?usp=sharing

**Comment by Bhavinjain260** [comment]
try adding SMCDellSensor kext 

https://github.com/acidanthera/VirtualSMC/releases

**Comment by Bhavinjain260** [comment]
> No, I'm not using this kext. Here is my EFI.
> 
> https://drive.google.com/file/d/10aszDx5OMABm1QamRtykjIyNBtLmyO91/view?usp=sharing

https://we.tl/t-Nej7PcGmG1

**Comment by macpromax** [comment]
I added the SMCDellSensor kext. And my issue is resolved. Thank you so much
