### ISSUE TITLE
 ocb startimage failed - aborted

### ISSUE THREAD

**Issue by dragonking91** [Bhavinjain260/Hackintosh-dell-inspiron-5559#4]
I get this issue
Here is a log: https://app.box.com/s/9quuoc9qrcc6m52n1hm5t2xa6cksxdo5

I use your EFI, just edit by GenSMBIOS

**Comment by Bhavinjain260** [comment]
What settings you have enabled and disabled in bios?

**Comment by dragonking91** [comment]
> What settings you have enabled and disabled in bios?
Boot Sequence >>UEFI,
Advanced boot options>> none stick "Enable Legacy option ROMS"
Sata operation >>AHCI
Drives: stick SATA-0 and SATA-1
USB/Thunderbolt Configuration: stick "enable USB boot support" and "Enable external usb port"
PTT security: none stick "PTT On" and "Clear"
Secure boot enable >> Disabled
Intel SGX Enable>>Disabled
Enable Intel Virtualization Technology
Disable VT for direct I/O

**Comment by dragonking91** [comment]
I fix change:
Open config.plist and under Booter > Quirks set DevirtualiseMmio to True 
Change SystemProductName MacbookPro13,1 to MacbookPro 13,2 and MLB, serial,.. follow GenSMBIOS
Import IntelBTPatcher.kext
I got new issue: https://app.box.com/s/i151tcbthywx31y1j037xe8tvvpt5t1s

**Comment by Bhavinjain260** [comment]
What new issue?
