### ISSUE TITLE
Failing to Boot The  BaseSystem

### ISSUE THREAD

**Issue by abbieben07** [Bhavinjain260/Hackintosh-dell-inspiron-5559#6]
Hello, I have an old Dell Inspiron 5559, I wish to install Big Sur, after following all your steps i face this error, please can you help me out
 
[opencore-2022-11-04-070042.txt](https://github.com/Bhavinjain260/Hackintosh-dell-inspiron-5559/files/9935820/opencore-2022-11-04-070042.txt)

**Comment by Bhavinjain260** [comment]
What options are enabled in BIOS?
And share a photo where you face an error
