### ISSUE TITLE
Touch does not work

### ISSUE THREAD

**Issue by HexagonWin** [Bhavinjain260/Hackintosh-dell-inspiron-5559#9]
Hello.

I have an Inspiron 5559 as well and successfully installed Mojave (10.14.6) with OpenCore from this repository. (I needed some minor modifications to the config.plist, and I removed non-relevant kexts (like sidecar) and upgraded them to the latest as well)
However I can't get touch to work. I guess your 5559 doesn't have the touch function as you haven't included kexts like VoodooI2CHID.kext...

Anyhow.. I did try adding the relevant kexts and everything else works (except for cam, which i disabled from BIOS) but not touch. Could you please give me an advice where I should look (if you know)?

**Comment by Bhavinjain260** [comment]
Share me your EFI 

For trackpad we are using SSDT-I2C-SKL.aml+ SSDT-XOSI.aml with SSDT XOSI patch and VoodooRMI.kext + VoodooI2C.kext

**Comment by HexagonWin** [comment]
@Bhavinjain260 What I mean is the touch in screen (touch panel), not the touch function for trackpad. Is this nonfunctional for you as well? Or maybe your 5559 doesn't have the feature built in at all?

**Comment by Bhavinjain260** [comment]
Yes, My Devices is not having the touch screen
